version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo installing dependencies
      - cd _infrastructure
      - npm install --legacy-peer-deps
      - cd ..
      - cd frontend
      - npm install --legacy-peer-deps
      - echo installing angular cli
      - npm i -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - echo Building frontend
      - ng build --configuration=test
artifacts:
  files:
    - '**/*'
  base-directory: 'frontend/dist/frontend'
