version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo installing dependencies
      - cd _infrastructure
      - npm install
      - cd ..
      - cd frontend
      - npm install --legacy-peer-deps
      - echo installing angular cli
      - npm i -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - echo Building frontend
      - ng build
    artifacts:
      files:
        - '**/*'
      base-directory: 'dist/frontend'
      discard-paths: 'yes'
