version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - n 18
      - echo installing dependencies
      - cd _infrastructure
      - npm install --legacy-peer-deps
      - cd ..
      - cd frontend
      - npm install --legacy-peer-deps
      - echo installing angular cli
      - npm i -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - echo Building frontend
      - echo "API_URL is $API_URL"
      - |
        sed -i "s|API_URL: ''|API_URL: '$API_URL'|" src/environments/environment.test.ts
      - ng build --configuration=test
artifacts:
  files:
    - '**/*'
  base-directory: 'frontend/dist/frontend'
